### ISSUE TITLE
http-log-pathが/dev/stdoutに出力されていない

### ISSUE THREAD

**Issue by marketspider** [prime-strategy/kusanagi-nginx#4]
Dockerfileに下記のようにhttp-log-pathの指定があるが、先頭のスラッシュが抜けている。
> 		--error-log-path=/dev/stderr \
>		--http-log-path=dev/stdout \

正しくは下記だと考えられる。
> 		--error-log-path=/dev/stderr \
>		--http-log-path=/dev/stdout \

**Comment by s-miyaza** [comment]
バグ報告ありがとうございます。

現在ビルド中の、kusanagi-nginx:1.19.2-r1 および kusanagi-nginx:1.18.0-r2 で上記の修正を行いました。
